package com.visibeat.coredb

import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey

@Entity(
  tableName = "metadata_observations",
  indices = [
    // Unique, and it was not before: the primary key is autogenerated, so
    // `OnConflictStrategy.IGNORE` on insert had no conflict to ignore and every
    // rescan appended a fresh copy of all ~20 observations for every track.
    // A library scanned three times carried three identical rows for each fact,
    // all of them read back through listBestFirst on every resolve.
    //
    // The leading columns match listBestFirst's filter, so this also replaces
    // the plain (subjectType, subjectId, field) index it supersedes.
    Index(
      value = ["subjectType", "subjectId", "field", "source", "value"],
      unique = true
    ),
    Index(value = ["field", "source"]),
    Index(value = ["observedAt"])
  ]
)
data class MetadataObservationEntity(
  @PrimaryKey(autoGenerate = true) val observationId: Long = 0,
  val subjectType: SubjectType,
  val subjectId: Long,
  val field: MetadataField,

  // Raw value from tag/source. Keep exactly as observed.
  // Dates: store ISO (supports partial, e.g. "1999" or "1999-06")
  val value: String,

  // For date fields; NONE otherwise
  val granularity: DateGranularity = DateGranularity.NONE,

  // Provenance + trust
  val source: MetaSource,
  val confidence: Confidence,

  // When we observed/wrote it (for tie-breaking + audit)
  val observedAt: Long
)
